[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.beautifulsoup4", "python3Packages.requests"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 main.py"
